CREATE DATABASE M_Peoples;

--DDL

USE M_Peoples;
GO

CREATE TABLE Funcionario(
IdFun				INT PRIMARY KEY IDENTITY,
NomeFun				VARCHAR(255) NOT NULL,
SobrenomeFun		VARCHAR(255) NOT NULL
);
GO

ALTER TABLE Funcionario ADD  DtNascimento DATE;

